Styling and login ui enhancement
TappedOpenSource/branding.tapped.ai pull request #14
Opened 2023-12-20 20:28 UTC by avidshotz

I fixed the styling scalability, and also made it so Firebase wouldn't get a create-account call until the confirm field matches the password field.

confirm field turns red if not completed properly.

demo:
https://www.loom.com/share/c6c416cdf7c541a294ef27cfa81ac6c9?sid=95d4f623-574e-424a-884c-566ac7806643

2023-12-21 22:14 UTC, jonaylor89 commented
The vercel check is failing. I can review this later tonight but can you fix that check in the meantime?

2023-12-22 23:43 UTC, jonaylor89 commented on package.json
> +    "next": "^14.0.4",
ummmmmmmmmm why?

2023-12-22 23:45 UTC, jonaylor89 commented on pages/signup.tsx
>    const [data, setData] = useState({
look how i do state in `login.tsx` and change it to be like that instead of one big object

i.e.
```js
const [email, setEmail] = useState...
const [password, setPassword] = useState..
const [confirmPassword, setconfirmPassword] = useState...
```

2023-12-22 23:45 UTC, jonaylor89 commented on pages/signup.tsx
> +  const [inputColor, setInputColor] = useState('white');
change this to `setError`

2023-12-22 23:46 UTC, jonaylor89 commented on pages/signup.tsx
> +              style={{borderColor: inputColor }} type = 'password'
this should change to something like `borderColor: error ? white : red`

2023-12-22 23:46 UTC, jonaylor89 requested changes
look at my comments and change accordingly

2023-12-23 00:53 UTC, avidshotz commented on package.json
> +    "next": "^14.0.4",
ill change it back to latest, not a problem

2023-12-23 02:27 UTC, avidshotz commented on pages/signup.tsx
>    const [data, setData] = useState({
the variables are formatted as requested

2023-12-29 20:52 UTC, jonaylor89 approved these changes
LGTM

2023-12-29 20:52 UTC, merged